### ISSUE TITLE
Unripe and ripe wheat looks a bit too similar

### ISSUE THREAD

**Issue by Laifsyn** [Faithful-Resource-Pack/Faithful-Java-32x#11]
So Age 6 and Age 7 Wheat looks a bit too similar. Is it intended?

![2022-02-23_01 03 04](https://user-images.githubusercontent.com/99366187/155269275-81c43a6e-5348-4ad6-817b-cdfafd334708.png)
![2022-02-23_01 06 05](https://user-images.githubusercontent.com/99366187/155269281-21e19b66-f4bc-45db-967f-626002699f6a.png)

**Comment by Lorenzo0310200** [comment]
yes

**Comment by 3vorp** [comment]
oh I completely forgot about this, I made a new wheat stage 6 texture because of this comment and the texture passed voting so in the next beta (or if you just download/clone off the github here) they should be a bit more distinct now
