### ISSUE TITLE
Missing fish textures in 1.8.9

### ISSUE THREAD

**Issue by mqtrx** [Faithful-Resource-Pack/Faithful-Java-32x#17]
Did someone forget to add fish textures for 1.8.9?
![image](https://user-images.githubusercontent.com/94565446/177060433-bb3f1899-6662-417b-b422-dc2f67f2e6e3.png)

**Comment by Pomi108** [comment]
This was done on purpose. Seeing as Jappa himself made [this texture](https://media.discordapp.net/attachments/779363363158229004/993396742018056202/magnified.png), the general consensus is that the colour change of the fish texture in 1.13 is more specific to the Update Aquatic rarher than being an integral part of the Texture Update, i.e. that it wouldn't have happened if the Update Aquatic didn't. As a result, the old, more generic fish texture will keep its green colour in versions 1.12 and below.

**Comment by Pomi108** [comment]
Because nobody made the texture yet.
