### ISSUE TITLE
Extra pixel on one of the Optifine Red stained glass textures

### ISSUE THREAD

**Issue by mintyfenix** [Faithful-Resource-Pack/Faithful-Java-32x#18]
Path: assets\minecraft\optifine\ctm\glass\red_stained_glass\5.png 
![unknown](https://user-images.githubusercontent.com/92201643/178097360-943f2b72-eec4-405a-b3fb-64ebe5011c6a.png)

**Comment by RobertRR11** [comment]
fixed
