### ISSUE TITLE
Missing Villager textures in 1.12.2

### ISSUE THREAD

**Issue by TheWithCommands** [Faithful-Resource-Pack/Faithful-Java-32x#20]
As shown in the figure. Some versions also have this problem.
![2022-08-01_12 40 05](https://user-images.githubusercontent.com/67952504/182073725-92da2ba7-a991-425f-8297-6f1f9e68ea65.png)

**Comment by 3vorp** [comment]
These textures have not been completed yet, as until recently we only supported 1.18+. In the near future, when someone makes 1.13- villager textures, we'll add them to our backports and this issue will be entirely resolved. 

For the time being, to fill in the gaps you can use the 1.12 release of [Classic Faithful PA](https://faithfulpack.net/classicfaithful/32x-programmer-art).
