### ISSUE TITLE
Canvas crashes with newest version of Faithful 32x

### ISSUE THREAD

**Issue by B055-Man** [Faithful-Resource-Pack/Faithful-Java-32x#22]
System Information

    Minecraft Version:
    Canvas Version: 1.0.2487
    Operating System: Windows 11
    Graphics Card: 3060ti

Other mods and versions installed

    fabric api 0.62.0
    fabric loader 0.14.9
    newest version of faithful 32x

How you triggered the behavior

    start minecraft
    open options and enable faithful 32x
    click done

What you expected would happen

    The game would reload and the texture pack would be applied.

What actually happened

    The game crashed after reload.

Logs and screenshots

    https://mclo.gs/vDeXJWE

Extra

    This occurs with canvas basic pipeline and forget-me-not.
    Also tryed barebones resource pack and the game ran normally.
    faithfulpack.net
  
  https://github.com/vram-guild/canvas/issues/398

**Comment by Pomi108** [comment]
Faithful is a resource pack like any other. It only changes textures. You'll have to reach out to Canvas to resolve this issue.

**Comment by B055-Man** [comment]
I understand that however other resource packs do not have this issue. I have tried 3 and faithful is the only one that crashes.

**Comment by Pomi108** [comment]
Well, I don't know what to say to you, but I've got absolutely zero idea what could be causing the issue. Again, the people behind Canvas will know better.
