### ISSUE TITLE
Beta 1.8.1 version please

### ISSUE THREAD

**Issue by glowiak** [Faithful-Resource-Pack/Faithful-Java-32x#23]
it's such a good version to play, would be good to have faithful on

**Comment by Pomi108** [comment]
If there's enough demand then sure, but I don't wanna manintain another legacy version just because there's (so far) only one person who'd want that

**Comment by 3vorp** [comment]
I can't really think of any breaking changes off the top of my head between 1.4 and b1.8, maybe a few entities slightly changed formatting, but for the most part you should be able to just use that really
