### ISSUE TITLE
1.19.3 missing textures

### ISSUE THREAD

**Issue by ShaneBeee** [Faithful-Resource-Pack/Faithful-Java-32x#24]
Hello

I just downloaded the latest pack for 1.19.3 today.
I noticed that there were some missing textures:
- all hanging signs
- bamboo regular sign

This is all I have noticed so far.
Thanks for all the hard work!

**Comment by Pomi108** [comment]
Hi, the 1.19.3 pack is not 100% complete. That's why it's labelled as a Pre-release. (As opposed to a regular release.) If you want to help get it done, you can join our Discord server.

**Comment by ShaneBeee** [comment]
Hi thanks for the update.
That's my bad, I didn't see anything regarding pre-release here:

<img width="852" alt="Screenshot 2022-12-09 at 2 23 31 PM" src="https://user-images.githubusercontent.com/20008482/206805415-b1b0f0b6-8a63-4af1-ad7b-7ece328f6c0e.png">


I'd love to help, but I don't know the first thing about graphics

**Comment by Pomi108** [comment]
Hm, didn't realise we don't distinguish this stuff on the downloads page. I was referring to the update post. Well, we're currently in the process of rewriting the website, so this would be the perfect time to implement such a tag (along with a multi-tag system). It would be great if you could make a suggestion ticket on our Website repository regarding this

**Comment by ShaneBeee** [comment]
> Hm, didn't realise we don't distinguish this stuff on the downloads page. I was referring to the update post. Well, we're currently in the process of rewriting the website, so this would be the perfect time to implement such a tag (along with a multi-tag system). It would be great if you could make a suggestion ticket on our Website repository regarding this

will do 👍
