### ISSUE TITLE
Outlines of some gui buttons are messed up

### ISSUE THREAD

**Issue by dvelasco734** [Faithful-Resource-Pack/Faithful-Java-32x#27]

**Comment by dvelasco734** [comment]
most noticeable on the cancel button when you connect to a realm

**Comment by Pomi108** [comment]
Got a pic?

**Comment by dvelasco734** [comment]
the outlines of some of the buttons are messed up
![image](https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/assets/56180307/db5c583a-c4d2-4df7-a817-90e6f7c97a0c)
![image](https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/assets/56180307/0860e9e5-5dff-409b-afe9-e4ac5b778db3)
