### ISSUE TITLE
Bamboo-Fence wrong texture

### ISSUE THREAD

**Issue by jonaas13** [Faithful-Resource-Pack/Faithful-Java-32x#32]
The bamboo fence textures is wrong. Black lines/dots across it. It's because it's using the wrong layout.

![bamboo-fence-bug](https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/assets/7745750/8f8c5f00-5de1-4e10-a3df-40a3b98e9e23)

I have attempted a manual fix but the texture looks a bit od now:

![bamboo_fence_gate](https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/assets/7745750/dbe94bc3-a1a5-47d9-b77e-8d44f712f15f)

![bamboo-fence-fixed](https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/assets/7745750/052e9d33-c6ff-4c0e-a18e-73f9927aae5c)

**Comment by Pomi108** [comment]
You are using the pack in the wrong version of the game. Please use it in the version it's labelled for (e.g. "Faithful 32x – 1.20.1" in 1.20.1).

**Comment by jonaas13** [comment]
> You are using the pack in the wrong version of the game. Please use it in the version it's labelled for (e.g. "Faithful 32x – 1.20.1" in 1.20.1).

Oh Oops, I didn't know there was a change between those 2. Alright I'll close the issue.
