### ISSUE TITLE
Why ores have 16x Texture

### ISSUE THREAD

**Issue by 1Grobotron1** [Faithful-Resource-Pack/Faithful-Java-32x#33]
![2024-01-21_14 39 42](https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/assets/153846880/2fff5e64-5932-4bad-b21a-6cea94ef943b)

**Comment by RobertRR11** [comment]
Because of other mods or resource packs you have enabled

**Comment by 1Grobotron1** [comment]
> Because of other mods or resource packs you have enabled

I have all the mods for optimization and all the effects, but not for textures, and resource packs only on 32x

**Comment by minimiscus** [comment]
if you wanna get your issue solved you probably want to join the discord server and make forum issue https://discord.com/channels/773983706582482946/1048179404737626184

**Comment by RobertRR11** [comment]
> I have all the mods for optimization and all the effects, but not for textures, and resource packs only on 32x

You definitely have some mod or resource pack installed that changes the ore texture, because that definitely is not the default coal ore

**Comment by 1Grobotron1** [comment]
> > I have all the mods for optimization and all the effects, but not for textures, and resource packs only on 32x
> 
> You definitely have some mod or resource pack installed that changes the ore texture, because that definitely is not the default coal ore

Its 1.20.1
