### ISSUE TITLE
Add snapshot branch?

### ISSUE THREAD

**Issue by Loweredgames** [Faithful-Resource-Pack/Faithful-Java-32x#34]
I was thinking that it would be convenient to add a branch that is only updated for snapshots (in this case 1.20.5). And just an idea that came to me

**Comment by DMgaming100** [comment]
it exsits already, java-latest is always using the latest version, including snapshots.
thats why we have both java-latest and 1.20.4

**Comment by Loweredgames** [comment]
> it exsits already, java-latest is always using the latest version, including snapshots.
> thats why we have both java-latest and 1.20.4

OK
