### ISSUE TITLE
Support for 1.21.3 :)?

### ISSUE THREAD

**Issue by Chromeyyy** [Faithful-Resource-Pack/Faithful-Java-32x#38]
As the title states, can you please provide support for 1.21.3?

**Comment by blryface** [comment]
Isn't that what the `java-snapshot` branch is for?

**Comment by Chromeyyy** [comment]
No. I don't think so.

**Comment by DMgaming100** [comment]
Java-latest is 1.21.3
Java-snapshot is the 1.21.4 snapshots

**Comment by Chromeyyy** [comment]
so i choose java latest branch and click code then download zip?

**Comment by Chromeyyy** [comment]
Nevermind, I learned how to read. Thanks
